apiVersion: v1
kind: Namespace
metadata:
  name: zeus
---
apiVersion: v1
kind: Service
metadata:
  name: zeus
  namespace: zeus
  labels:
    app: zeus
spec:
  ports:
  - port: 8080
    name: zeus
  type: NodePort
  selector:
    app: zeus
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeus
  namespace: zeus
spec:
  serviceName: "zeus"
  replicas: 1
  template:
    metadata:
      labels:
        app: zeus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zeus
          image: promartio/zeus
          ports:
            - containerPort: 8080
              name: zeus
          volumeMounts:
            - name: root
              mountPath: /usr/local/tomcat/dirigible
      serviceAccountName: service-account
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: zeus
  namespace: zeus
spec:
  rules:
    - host: zeus.ingress.dev.promart.shoot.canary.k8s-hana.ondemand.com
      http:
        paths:
          - path: /
            backend:
              serviceName: zeus
              servicePort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: zeus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeus
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zeus
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: zeus
