apiVersion: v1
kind: Namespace
metadata:
  name: zeus
---
apiVersion: v1
kind: Service
metadata:
  name: zeus
  namespace: zeus
  labels:
    app: zeus
spec:
  ports:
  - port: 8080
    name: zeus
  type: NodePort
  selector:
    app: zeus
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeus
  namespace: zeus
spec:
  serviceName: "zeus"
  replicas: 1
  template:
    metadata:
      labels:
        app: zeus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: dirigible
          image: zeus
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: zeus
          volumeMounts:
            - name: root
              mountPath: /usr/local/tomcat/dirigible
          env:
            - name: localRepositoryRootFolder
              value: /usr/local/tomcat/dirigible/repository
            - name: localRepositoryRootFolderIsAbsolute
              value: "true"
            - name: localDatabaseRootFolder
              value: /usr/local/tomcat/dirigible/derby
            - name: localCmisRootFolder
              value: /usr/local/tomcat/dirigible/cmis
            - name: initLoggingDirectory
              value: /tomcat/logs
            - name: repositoryProviderMaster
              value: git
            - name: masterRepositoryGitTarget
              value: master_git_repository
            - name: masterRepositoryGitLocation
              value: https://github.com/dirigiblelabs/zeus_setup.git
            - name: masterRepositoryGitBranch
              value: origin/master
      serviceAccountName: zeus
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: zeus
  namespace: zeus
spec:
  rules:
    - host: zeus.apps.eu-central-1.sap.onvms.com
      http:
        paths:
          - path: /
            backend:
              serviceName: zeus
              servicePort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeus
  namespace: zeus
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: zeus
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: zeus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zeus
subjects:
  - kind: ServiceAccount
    name: zeus
    namespace: zeus
